[project]
name = "dynamical-systems"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Joon-Hyuk Ko", email = "jhko725@kias.re.kr" }
]
requires-python = ">=3.12"
dependencies = [
    "diffrax>=0.6.2",
    "equinox>=0.11.12",
    "jax[cuda12]>=0.5.2",
    "jaxtyping>=0.2.38",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
