defaults:
  - _self_
  - model: neuralode
  - data: lorenz63_dyslim
  - training: base
  - override hydra/launcher: submitit_slurm

jacobian:
  weight: 1.0
  chunk_size: null

hydra:
  launcher: 
    timeout_min: 900
    tasks_per_node: 1
    gpus_per_node: 1

enable_x64: true
