defaults:
  - base

_target_: dynamics_discovery.models.NeuralODE
width: 32
depth: 3
activation: 
  _target_: hydra.utils.get_method
  path: jax.nn.gelu
solver: 
  _target_: diffrax.Tsit5
rtol: 1e-4
atol: 1e-6