[project]
name = "dynamics-discovery"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Joon-Hyuk Ko", email = "jhko725@kias.re.kr" }
]
requires-python = ">=3.12"
dependencies = [
    "equinox>=0.11.12",
    "jax[cuda12]>=0.5.2",
]

[project.scripts]
dynamics-discovery = "dynamics_discovery:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
