_target_: ???
optimizer:
  _target_: optax.adabelief
  learning_rate: 1e-3
loss_fn:
  _target_: dynamics_discovery.loss_functions.MSELoss
  batch_size: null
max_epochs: 2000
savedir: ./results/${..data.name}_final/
savename: len=${..preprocessing.batch_length}_downsample=${preprocessing.downsample.keep_every}_noise=${..preprocessing.noise.rel_noise_strength}_key=${..model.key}.eqx
wandb_entity: jhko725
wandb_project: ${..data.name}