defaults:
  - base

_target_: dynamics_discovery.training.VanillaTrainer
loss_fn:
  _target_: dynamics_discovery.loss_functions.MSELoss
  batch_size: null
savedir: ./results/${..data.name}_final/
savename: len=${..preprocessing.batch_length}_downsample=${preprocessing.downsample.keep_every}_noise=${..preprocessing.noise.rel_noise_strength}_key=${..model.key}.eqx